CREATE TABLE `rules` (
  `realm_name` varchar(20) NOT NULL,
  `id` binary(16) NOT NULL,
  `create_type` enum('user','system') NOT NULL DEFAULT 'user',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `auto_apply` tinyint(1) NOT NULL DEFAULT '0',
  `target_id` binary(16) NOT NULL,
  `metric_rule_uid` varchar(50) NOT NULL,
  `info_threshold` double DEFAULT NULL,
  `warn_threshold` double DEFAULT NULL ,
  `crit_threshold` double DEFAULT NULL,
  `duration` varchar(10) NOT NULL DEFAULT '5m',
  `silence_period` varchar(10) NOT NULL DEFAULT '1h',
  `times` int NOT NULL DEFAULT '3',
  `created_by` varchar(36) DEFAULT NULL,
  `updated_by` varchar(36) DEFAULT NULL,
  `created_at` bigint unsigned DEFAULT NULL,
  `updated_at` bigint unsigned DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule` (`realm_name`,`metric_rule_uid`,`target_id`),
  KEY `fk_realms_rules` (`realm_name`),
  CONSTRAINT `fk_realms_rules` FOREIGN KEY (`realm_name`) REFERENCES `realms` (`name`),
  CONSTRAINT `fk_targets_rules` FOREIGN KEY (`target_id`) REFERENCES `targets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;