CREATE TABLE `triggered_logs` (
  `realm_name` varchar(50) NOT NULL,
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `timestamp` bigint NOT NULL,
  `rule_id` VARCHAR(36) NOT NULL,
  `rule_name` varchar(255) NOT NULL,
  `resource_group_name` varchar(100) NOT NULL,
  `resource_name` varchar(100) NOT NULL,
  `partition_name` varchar(100) DEFAULT NULL,
  `metric_name` varchar(100) NOT NULL,
  `unit` varchar(10) NOT NULL,
  `triggered_value` decimal(10,2) NOT NULL,
  `threshold` decimal(10,2) NOT NULL,
  `severity` enum('info','warn','crit') NOT NULL,
  `first_triggered_time` bigint DEFAULT NULL,
  `silence_start` bigint DEFAULT NULL,
  `silence_end` bigint DEFAULT NULL,
  `mute_start` bigint DEFAULT NULL,
  `mute_end` bigint DEFAULT NULL,
  `contact_state` enum('normal','muting','silence') NOT NULL,
  `resolved_time` bigint DEFAULT NULL,
  `notify_state` enum('solved','failed') DEFAULT NULL,
  `resolved_notify_state` enum('solved','failed') DEFAULT NULL,
  `created_at` bigint unsigned DEFAULT NULL,
  `updated_at` bigint unsigned DEFAULT NULL,
  INDEX `idx_triggered_log` (`id`),
  KEY `fk_triggered_logs_realms` (`realm_name`),
  CONSTRAINT `fk_triggered_logs_realms` FOREIGN KEY (`realm_name`) REFERENCES `realms` (`name`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_rule_id` (`rule_id`),
  KEY `idx_notify_state` (`notify_state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

