// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alert/contact": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有聯絡人 [ID, Name, Type, Enabled]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "獲取聯絡人列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "created_at",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大筆數",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "無效的 ID",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新增一條聯絡人",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "創建聯絡人",
                "parameters": [
                    {
                        "description": "聯絡人內容",
                        "name": "contact",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ContactResponse"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "成功創建",
                        "schema": {
                            "$ref": "#/definitions/models.ContactResponse"
                        }
                    },
                    "400": {
                        "description": "請求內容無效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/contact/notify-methods": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有通知方法",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "獲取通知方法",
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/contact/notify-options": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有通知選項",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "獲取通知選項",
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/contact/test": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "測試聯絡人是否能夠收到通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "測試聯絡人",
                "parameters": [
                    {
                        "description": "聯絡人內容",
                        "name": "contact",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ContactResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "請求內容無效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/contact/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據 ID 獲取特定的聯絡人",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "獲取單一聯絡人",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "聯絡人 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "$ref": "#/definitions/models.ContactResponse"
                        }
                    },
                    "400": {
                        "description": "無效的 ID",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據 ID 更新聯絡人內容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "更新聯絡人",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "聯絡人 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "聯絡人內容",
                        "name": "contact",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ContactResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功更新",
                        "schema": {
                            "$ref": "#/definitions/models.ContactResponse"
                        }
                    },
                    "400": {
                        "description": "請求內容無效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據 ID 刪除聯絡人",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "刪除聯絡人",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "聯絡人 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刪除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "無效的 ID",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有告警歷史",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alert"
                ],
                "summary": "獲取告警歷史列表",
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.TriggeredLog"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/rule": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有規則 [ID, Name, Type, Enabled]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "獲取規則列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "created_at",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大筆數",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "無效的 ID",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新增一條規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "創建規則",
                "parameters": [
                    {
                        "description": "規則內容",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Rule"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "成功創建",
                        "schema": {
                            "$ref": "#/definitions/models.Rule"
                        }
                    },
                    "400": {
                        "description": "請求內容無效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/rule/manual-notify": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "手動觸發指定規則的通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "手動觸發通知",
                "parameters": [
                    {
                        "description": "手動通知請求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ManualNotifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知已觸發",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "請求內容無效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/rule/metric-rule-category-options": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有告警規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alert"
                ],
                "summary": "獲取告警規則列表",
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Rule"
                            }
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/rule/metric-rule-options/{category}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有告警規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alert"
                ],
                "summary": "獲取告警規則列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "規則類別",
                        "name": "category",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Rule"
                            }
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/rule/metric-rule/{uid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得規則詳細",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alert"
                ],
                "summary": "獲取規則詳細",
                "parameters": [
                    {
                        "type": "string",
                        "description": "規則 UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Rule"
                            }
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/rule/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據 ID 獲取特定的規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "獲取單一規則",
                "parameters": [
                    {
                        "type": "string",
                        "description": "規則 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "$ref": "#/definitions/models.Rule"
                        }
                    },
                    "400": {
                        "description": "無效的 ID",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據 ID 更新規則內容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "更新規則",
                "parameters": [
                    {
                        "type": "string",
                        "description": "規則 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "規則內容",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Rule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功更新",
                        "schema": {
                            "$ref": "#/definitions/models.Rule"
                        }
                    },
                    "400": {
                        "description": "請求內容無效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據 ID 刪除規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "刪除規則",
                "parameters": [
                    {
                        "type": "string",
                        "description": "規則 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刪除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "無效的 ID",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/run-alert": {
            "post": {
                "description": "告警處理",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Alert"
                ],
                "summary": "告警處理",
                "parameters": [
                    {
                        "description": "檢測數據",
                        "name": "alertPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AlertPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/run-notify": {
            "post": {
                "description": "批次通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alert"
                ],
                "summary": "立即通知",
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/alert/state": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "取得所有告警狀態",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alert"
                ],
                "summary": "獲取告警狀態列表",
                "responses": {
                    "200": {
                        "description": "成功回應",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RuleState"
                            }
                        }
                    },
                    "500": {
                        "description": "伺服器錯誤",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/rules": {
            "get": {
                "description": "列出所有規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "列出規則",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "游標",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "限制",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.MetricRuleOverview"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "創建一個新的規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "創建規則",
                "parameters": [
                    {
                        "description": "規則信息",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RuleResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RuleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/rules/{id}": {
            "put": {
                "description": "更新現有規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "更新規則",
                "parameters": [
                    {
                        "type": "string",
                        "description": "規則 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "規則信息",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RuleResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RuleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除現有規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "刪除規則",
                "parameters": [
                    {
                        "type": "string",
                        "description": "規則 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/rules/{metricRuleUID}": {
            "get": {
                "description": "根據 metricRuleUID 獲取規則",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "獲取規則",
                "parameters": [
                    {
                        "type": "string",
                        "description": "指標規則 UID",
                        "name": "metricRuleUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RuleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/rules/{metricRuleUID}/targets": {
            "get": {
                "description": "獲取可用的監控目標",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "獲取可用的監控目標",
                "parameters": [
                    {
                        "type": "string",
                        "description": "指標規則 UID",
                        "name": "metricRuleUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Target"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "alert.Contact": {
            "type": "object",
            "properties": {
                "auto_apply": {
                    "type": "boolean"
                },
                "channel_type": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/common.JSONMap"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "max_retry": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "realm_name": {
                    "type": "string"
                },
                "retry_delay": {
                    "type": "string"
                },
                "send_resolved": {
                    "type": "boolean"
                },
                "severities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "alert.Metadata": {
            "type": "object",
            "properties": {
                "datasource_name": {
                    "type": "string"
                },
                "realm_name": {
                    "type": "string"
                },
                "resource_name": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "告警發送時間",
                    "type": "integer"
                }
            }
        },
        "alert.MetricRule": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "detection_type": {
                    "type": "string"
                },
                "display_unit": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "match_datasource_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "match_target_pattern": {
                    "type": "string"
                },
                "metric_display_name": {
                    "type": "string"
                },
                "metric_raw_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "raw_unit": {
                    "type": "string"
                },
                "scale": {
                    "type": "number"
                },
                "thresholds": {
                    "$ref": "#/definitions/alert.Threshold"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "alert.MetricValue": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "description": "數據發生時間",
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "alert.RuleContactResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "severities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "alert.RuleResponse": {
            "type": "object",
            "properties": {
                "auto_apply": {
                    "type": "boolean"
                },
                "contacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.RuleContactResponse"
                    }
                },
                "crit_threshold": {
                    "type": "number"
                },
                "duration": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "info_threshold": {
                    "type": "number"
                },
                "metric_rule": {
                    "$ref": "#/definitions/alert.MetricRule"
                },
                "silence_period": {
                    "type": "string"
                },
                "target": {
                    "$ref": "#/definitions/alert.Target"
                },
                "times": {
                    "type": "integer"
                },
                "warn_threshold": {
                    "type": "number"
                }
            }
        },
        "alert.Target": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "collection_interval": {
                    "type": "integer"
                },
                "datasource_name": {
                    "type": "string"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "is_hidden": {
                    "type": "boolean"
                },
                "partition_name": {
                    "type": "string"
                },
                "realm_name": {
                    "type": "string"
                },
                "reporting_interval": {
                    "type": "integer"
                },
                "resource_name": {
                    "type": "string"
                }
            }
        },
        "alert.Threshold": {
            "type": "object",
            "properties": {
                "crit": {
                    "type": "number"
                },
                "info": {
                    "type": "number"
                },
                "warn": {
                    "type": "number"
                }
            }
        },
        "common.JSONMap": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "controller.ManualNotifyRequest": {
            "type": "object",
            "required": [
                "ruleIds"
            ],
            "properties": {
                "ruleIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.AlertPayload": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "監控數據",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/alert.MetricValue"
                        }
                    }
                },
                "metadata": {
                    "description": "告警元數據",
                    "$ref": "#/definitions/alert.Metadata"
                }
            }
        },
        "models.ContactResponse": {
            "type": "object",
            "properties": {
                "auto_apply": {
                    "type": "boolean"
                },
                "channel_type": {
                    "type": "string"
                },
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "max_retry": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "retry_delay": {
                    "type": "string"
                },
                "send_resolved": {
                    "type": "boolean"
                },
                "severities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.MetricRuleOverview": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "指標規則類型",
                    "type": "string"
                },
                "contact_count": {
                    "description": "通知通道數量",
                    "type": "integer"
                },
                "metric_rule_name": {
                    "description": "指標規則名稱",
                    "type": "string"
                },
                "metric_rule_uid": {
                    "description": "指標規則UID",
                    "type": "string"
                },
                "partition_count": {
                    "description": "監控分區數量",
                    "type": "integer"
                },
                "rule_count": {
                    "description": "規則數量",
                    "type": "integer"
                },
                "rules": {
                    "description": "規則列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.RuleResponse"
                    }
                },
                "target_count": {
                    "description": "監控對象數量",
                    "type": "integer"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.Rule": {
            "type": "object",
            "properties": {
                "auto_apply": {
                    "type": "boolean"
                },
                "contacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.Contact"
                    }
                },
                "create_type": {
                    "type": "string"
                },
                "crit_threshold": {
                    "type": "number"
                },
                "duration": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "info_threshold": {
                    "type": "number"
                },
                "metric_rule_uid": {
                    "type": "string"
                },
                "realm_name": {
                    "type": "string"
                },
                "silence_period": {
                    "type": "string"
                },
                "target": {
                    "$ref": "#/definitions/alert.Target"
                },
                "target_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "times": {
                    "type": "integer"
                },
                "warn_threshold": {
                    "type": "number"
                }
            }
        },
        "models.RuleResponse": {
            "type": "object",
            "properties": {
                "auto_apply": {
                    "type": "boolean"
                },
                "contacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/alert.RuleContactResponse"
                    }
                },
                "crit_threshold": {
                    "type": "number"
                },
                "duration": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "info_threshold": {
                    "type": "number"
                },
                "metric_rule": {
                    "$ref": "#/definitions/alert.MetricRule"
                },
                "silence_period": {
                    "type": "string"
                },
                "target": {
                    "$ref": "#/definitions/alert.Target"
                },
                "times": {
                    "type": "integer"
                },
                "warn_threshold": {
                    "type": "number"
                }
            }
        },
        "models.RuleState": {
            "type": "object",
            "properties": {
                "contact_counter": {
                    "type": "integer"
                },
                "contact_state": {
                    "type": "string"
                },
                "first_triggered_at": {
                    "type": "integer"
                },
                "last_check_value": {
                    "type": "number"
                },
                "last_triggered_at": {
                    "type": "integer"
                },
                "last_triggered_log_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "last_triggered_severity": {
                    "type": "string"
                },
                "last_triggered_value": {
                    "type": "number"
                },
                "rule_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "silence_end_at": {
                    "type": "integer"
                },
                "silence_start_at": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "models.Target": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "collection_interval": {
                    "type": "integer"
                },
                "datasource_name": {
                    "type": "string"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "is_hidden": {
                    "type": "boolean"
                },
                "partition_name": {
                    "type": "string"
                },
                "realm_name": {
                    "type": "string"
                },
                "reporting_interval": {
                    "type": "integer"
                },
                "resource_name": {
                    "type": "string"
                }
            }
        },
        "models.TriggeredLog": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "last_triggered_at": {
                    "type": "integer"
                },
                "metric_rule_uid": {
                    "type": "string"
                },
                "notify_log_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "notify_state": {
                    "type": "string"
                },
                "partition_name": {
                    "type": "string"
                },
                "realm_name": {
                    "type": "string"
                },
                "resolved_at": {
                    "type": "integer"
                },
                "resolved_notify_log_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "resolved_notify_state": {
                    "type": "string"
                },
                "resolved_value": {
                    "type": "number"
                },
                "resource_name": {
                    "type": "string"
                },
                "rule_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "rule_snapshot": {
                    "$ref": "#/definitions/common.JSONMap"
                },
                "rule_state_snapshot": {
                    "$ref": "#/definitions/common.JSONMap"
                },
                "severity": {
                    "type": "string"
                },
                "threshold": {
                    "type": "number"
                },
                "triggered_at": {
                    "description": "first",
                    "type": "integer"
                },
                "triggered_value": {
                    "type": "number"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Shared-lib API",
	Description:      "提供告警、通知、規則管理等功能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
