// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package alert

import (
	"github.com/detect-viz/shared-lib/auth/keycloak"
	"github.com/detect-viz/shared-lib/contacts"
	"github.com/detect-viz/shared-lib/infra/logger"
	"github.com/detect-viz/shared-lib/infra/scheduler"
	"github.com/detect-viz/shared-lib/labels"
	"github.com/detect-viz/shared-lib/models"
	"github.com/detect-viz/shared-lib/models/config"
	"github.com/detect-viz/shared-lib/notifier"
	"github.com/detect-viz/shared-lib/rules"
	"github.com/detect-viz/shared-lib/storage/mysql"
	"github.com/detect-viz/shared-lib/templates"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeAlertService 初始化 AlertService
func InitializeAlertService(config2 config.AlertConfig, global config.GlobalConfig, mysqlClient *mysql.Client, log logger.Logger, keycloakClient *keycloak.Client) (*Service, error) {
	globalConfig := ProvideGlobalConfig(global)
	serviceImpl := rules.NewService(mysqlClient, log, globalConfig)
	service := ProvideNotifierService(keycloakClient)
	contactsServiceImpl := contacts.NewService(mysqlClient, log, service, keycloakClient)
	schedulerServiceImpl := scheduler.NewService(log)
	templatesServiceImpl := templates.NewService(log)
	alertService := ProvideAlertService(config2, global, mysqlClient, log, serviceImpl, service, contactsServiceImpl, schedulerServiceImpl, templatesServiceImpl)
	return alertService, nil
}

// wire.go:

// 提供 zap.Logger
func ProvideZapLogger(log logger.Logger) *zap.Logger {
	if log == nil {
		panic("❌ log 是 nil")
	}
	return log.GetLogger()
}

// 提供 GlobalConfig
func ProvideGlobalConfig(global models.GlobalConfig) *models.GlobalConfig {
	return &global
}

// 提供 notifier.Service
func ProvideNotifierService(keycloakClient *keycloak.Client) notifier.Service {
	return notifier.NewService(keycloakClient)
}

// 提供 scheduler.Service
func ProvideSchedulerService(log logger.Logger) scheduler.Service {
	return scheduler.NewService(log)
}

// 提供 templates.Service
func ProvideTemplateService(log logger.Logger) templates.Service {
	return templates.NewService(log)
}

// 提供 labels.Service
func ProvideLabelService(mysqlClient *mysql.Client) labels.Service {
	return labels.NewService(mysqlClient)
}

// 提供 contacts.Service
func ProvideContactService(mysqlClient *mysql.Client, log logger.Logger, notifierService notifier.Service, keycloakClient *keycloak.Client) contacts.Service {
	return contacts.NewService(mysqlClient, log, notifierService, keycloakClient)
}

// AlertSet 提供所有依賴的 wire Set
var AlertSet = wire.NewSet(

	ProvideZapLogger,

	ProvideGlobalConfig,

	ProvideNotifierService,

	ProvideAlertService, rules.RuleSet, scheduler.SchedulerSet, templates.TemplateSet, contacts.ContactSet,
)

// ProvideAlertService 提供 AlertService 實例
func ProvideAlertService(config2 models.AlertConfig,

	global models.GlobalConfig,
	mysqlClient *mysql.Client,
	logSvc logger.Logger,
	rule rules.Service,
	notify notifier.Service,
	contact contacts.Service, scheduler2 scheduler.Service,

	template templates.Service,
) *Service {
	logSvc.Debug("檢查 ProvideAlertService 參數", zap.Any("config", config2), zap.Any("mysqlClient", mysqlClient))

	if mysqlClient == nil {
		panic("❌ mysqlClient 是 nil")
	}
	if logSvc == nil {
		panic("❌ logSvc 是 nil")
	}
	if notify == nil {
		panic("❌ notify 是 nil")
	}
	if contact == nil {
		panic("❌ contact 是 nil")
	}
	if scheduler2 == nil {
		panic("❌ scheduler 是 nil")
	}
	if template == nil {
		panic("❌ template 是 nil")
	}

	return NewService(config2, global,
		mysqlClient,
		logSvc,
		rule,
		notify,
		contact, scheduler2, template,
	)
}
