CREATE TABLE `alert_mutes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `realm_name` varchar(20) NOT NULL DEFAULT 'master',
  `name` varchar(50) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `start_time` int NOT NULL,
  `end_time` int NOT NULL,
  `state` varchar(50) DEFAULT 'disabled',
  `cron_expression` varchar(255) DEFAULT NULL,
  `cron_period` int DEFAULT NULL,
  `repeat_type` varchar(20) DEFAULT 'never',
  `never` tinyint(1) DEFAULT '1',
  `daily` tinyint(1) DEFAULT '0',
  `weekly` tinyint(1) DEFAULT '0',
  `monthly` tinyint(1) DEFAULT '0',
  `mon` tinyint(1) DEFAULT '0',
  `tue` tinyint(1) DEFAULT '0',
  `wed` tinyint(1) DEFAULT '0',
  `thu` tinyint(1) DEFAULT '0',
  `fri` tinyint(1) DEFAULT '0',
  `sat` tinyint(1) DEFAULT '0',
  `sun` tinyint(1) DEFAULT '0',
  `created_at` bigint unsigned DEFAULT NULL,
  `updated_at` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mute_name` (`realm_name`,`name`),
  KEY `idx_alert_mutes_realm` (`realm_name`),
  KEY `idx_alert_mutes_state` (`state`),
  CONSTRAINT `fk_mute_realms` FOREIGN KEY (`realm_name`) REFERENCES `realms` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;