CREATE TABLE `trigger_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `timestamp` bigint NOT NULL,
  `rule_id` varchar(50) NOT NULL,
  `rule_name` varchar(255) NOT NULL,
  `resource_group_name` varchar(100) NOT NULL,
  `resource_name` varchar(100) NOT NULL,
  `partition_name` varchar(100) DEFAULT NULL,
  `metric_name` varchar(100) NOT NULL,
  `value` decimal(10,2) NOT NULL,
  `threshold` decimal(10,2) NOT NULL,
  `unit` varchar(10) NOT NULL,
  `severity` enum('info','warn','crit') NOT NULL,
  `duration` int NOT NULL,
  `status` enum('alerting','resolved') NOT NULL DEFAULT 'alerting',
  `notify_status` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
  `notify_retry` int DEFAULT '0',
  `silence_start` bigint DEFAULT NULL,
  `silence_end` bigint DEFAULT NULL,
  `pending_end` bigint DEFAULT NULL,
  `resolved_time` bigint DEFAULT NULL,
  `first_trigger_time` bigint DEFAULT NULL,
  `labels` json DEFAULT NULL,
  `contacts` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_rule_id` (`rule_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

